---

- hosts: Nodes
  become: true
  become_method: sudo

  tasks:
  - name: Including vars
    include_vars:
      file: variables.yml
      name: params

  - name: Copying token to nodes
    copy: src={{ params.file }} dest=token

  - name: Joining kubernetes master
    shell: |
      iptables -P FORWARD ACCEPT
      cat token | tail -2 > out.sh
      sh out.sh