---

- hosts: Worker
  become: true
  become_method: sudo

  tasks:
  - name: Including vars
    include_vars:
      file: variables.yml
      name: params

  - name: Copying token to worker nodes
    copy: src={{ params.file }} dest=token

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat token | tail -2 > out.sh
     sh out.sh
